In [19]:
import pandas as pd

In [20]:
dfp = pd.read_csv("processed_movies.csv")
dfp.shape

(12138, 35)

In [21]:
dfi = pd.read_csv("imdbDataFinal.csv")
dfi.shape

(16103, 10)

In [23]:
dfn = dfp[~dfp['id'].isin(dfi['id'])]
dfn

,id,title,rating,year,actors_tsne_1,actors_tsne_2,type,Action,Adventure,Animation,...,Reality-TV,Romance,Sci-Fi,Short,Sport,Talk-Show,Thriller,War,Western,nan
4,tt0011130,Dr. Jekyll and Mr. Hyde,0.09375,0.045872,0.465815,0.403688,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
5,tt0011237,The Golem,0.18750,0.045872,0.333086,0.665133,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,tt0011841,Way Down East,0.21875,0.045872,0.378994,0.756628,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
7,tt0012349,The Kid,0.50000,0.055046,0.528072,0.760000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,tt0012364,The Phantom Carriage,0.43750,0.055046,0.181734,0.614855,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1331,tt0062550,The Bugs Bunny/Road Runner Hour,0.59375,0.486239,0.220509,0.460979,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
11524,tt7718110,Hightown,0.09375,0.963303,0.701178,0.839160,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11525,tt7720790,Forever,0.15625,0.944954,0.447856,0.727798,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11526,tt7725596,Badhaai Ho,0.40625,0.944954,0.691702,0.337771,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11527,tt7736478,The Traitor,0.15625,0.954128,0.540035,0.554061,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
dfn[["id"]].to_csv("nonp.csv", index=False)